openapi: 3.0.0
info:
  title: backend API
  version: "1.0"
paths:
  /status:
    get:
      summary: Get status
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 1
    post:
      summary: Set status
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: integer
      responses:
        '200':
          description: Status was changed
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 1
